name: seo
channels:
  - conda-forge
  - defaults
dependencies:
  - lxml
  - pip
  - requests
  - python=3.12
  - uwsgi
  - jinja2
  - flask
  - pytest
  - daiquiri
  - libiconv
  - pip:
      - soso
prefix: /opt/miniconda3/envs/seo
