name: seo
channels:
  - conda-forge
  - defaults
dependencies:
  - blinker=1.9.0
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - ca-certificates=2025.10.5
  - certifi=2025.10.5
  - cffi=2.0.0
  - charset-normalizer=3.4.4
  - click=8.3.0
  - colorama=0.4.6
  - daiquiri=3.0.0
  - exceptiongroup=1.3.0
  - flask=3.1.2
  - h2=4.3.0
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.11
  - importlib-metadata=8.7.0
  - iniconfig=2.3.0
  - itsdangerous=2.2.0
  - jansson=2.14.1
  - jinja2=3.1.6
  - libcxx=21.1.5
  - libexpat=2.7.1
  - libffi=3.5.2
  - libiconv=1.18
  - liblzma=5.8.1
  - libsqlite=3.51.0
  - libxcrypt=4.4.36
  - libxml2=2.15.1
  - libxml2-16=2.15.1
  - libxslt=1.1.43
  - libzlib=1.3.1
  - markupsafe=3.0.3
  - ncurses=6.5
  - openssl=3.6.0
  - packaging=25.0
  - pcre2=10.46
  - pip=25.3
  - pluggy=1.6.0
  - pycparser=2.22
  - pygments=2.19.2
  - pysocks=1.7.1
  - pytest=9.0.0
  - python=3.12.12
  - python-json-logger=2.0.7
  - python_abi=3.12
  - readline=8.2
  - requests=2.32.5
  - setuptools=80.9.0
  - tk=8.6.13
  - tomli=2.3.0
  - typing_extensions=4.15.0
  - tzdata=2025b
  - urllib3=2.5.0
  - uwsgi=2.0.31
  - werkzeug=3.1.3
  - wheel=0.45.1
  - yaml=0.2.5
  - zipp=3.23.0
  - zstandard=0.25.0
  - zstd=1.5.7
  - pip:
      - html5lib==1.1
      - lxml==5.4.0
      - owlrl==6.0.2
      - prettytable==3.16.0
      - pyparsing==3.2.5
      - pyshacl==0.26.0
      - rdflib==7.4.0
      - six==1.17.0
      - soso==0.4.0
      - wcwidth==0.2.14
      - webencodings==0.5.1
prefix: /opt/miniconda3/envs/seo
