name: seo
channels:
  - conda-forge
  - defaults
dependencies:
  - daiquiri
  - pip
  - python=3.12
  - uwsgi
  - pytest
  - jinja2
  - requests
  - flask
  - libiconv
prefix: /opt/miniconda3/envs/seo
