name: seo
channels:
  - conda-forge
  - defaults
dependencies:
  - lxml
  - pip
  - requests
  - python=3.12
  - uwsgi
  - jinja2
  - flask
  - pytest
  - daiquiri
  - libiconv
  - pip:
      - git+https://github.com/clnsmth/soso.git@v0.4.0
prefix: /opt/miniconda3/envs/seo
