name: seo
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - backports.zstd=1.3.0
  - blinker=1.9.0
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - ca-certificates=2026.1.4
  - certifi=2026.1.4
  - charset-normalizer=3.4.4
  - click=8.3.1
  - colorama=0.4.6
  - daiquiri=3.0.0
  - exceptiongroup=1.3.1
  - flask=3.1.2
  - h2=4.3.0
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=78.2
  - idna=3.11
  - importlib-metadata=8.7.0
  - iniconfig=2.3.0
  - itsdangerous=2.2.0
  - jansson=2.15.0
  - jinja2=3.1.6
  - ld_impl_linux-64=2.45
  - libexpat=2.7.3
  - libffi=3.5.2
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - libiconv=1.18
  - liblzma=5.8.2
  - libnsl=2.0.1
  - libsqlite=3.51.2
  - libstdcxx=15.2.0
  - libuuid=2.41.3
  - libxcrypt=4.4.36
  - libxml2=2.15.1
  - libxml2-16=2.15.1
  - libxslt=1.1.43
  - libzlib=1.3.1
  - markupsafe=3.0.3
  - ncurses=6.5
  - openssl=3.6.1
  - packaging=26.0
  - pcre2=10.47
  - pip=26.0
  - pluggy=1.6.0
  - pygments=2.19.2
  - pysocks=1.7.1
  - pytest=9.0.2
  - python=3.12.12
  - python-json-logger=2.0.7
  - python_abi=3.12
  - readline=8.3
  - requests=2.32.5
  - setuptools=80.10.2
  - tk=8.6.13
  - tomli=2.4.0
  - typing_extensions=4.15.0
  - tzdata=2025c
  - urllib3=2.6.3
  - uwsgi=2.0.31
  - werkzeug=3.1.5
  - wheel=0.46.3
  - yaml=0.2.5
  - zipp=3.23.0
  - zstd=1.5.7
  - pip:
      - html5lib==1.1
      - lxml==5.4.0
      - owlrl==6.0.2
      - prettytable==3.17.0
      - pyparsing==3.3.2
      - pyshacl==0.26.0
      - rdflib==7.5.0
      - six==1.17.0
      - soso==0.4.0
      - wcwidth==0.5.3
      - webencodings==0.5.1
prefix: /home/servilla/miniconda3/envs/seo
